import {
  ic_alert,
  ic_check_list,
  ic_delete_account,
  ic_device,
  ic_form_list,
  ic_heart,
  ic_help,
  ic_interaction,
  ic_location_grey,
  ic_package_delivery,
  ic_package_delivery1,
  ic_phonebook,
  ic_reload,
  ic_report,
  ic_setting,
  ic_store_default,
  ic_target,
  ic_task_management_grey,
  icon_user,
} from 'assets/images';
import {OtherMenuType} from '../enums';
import {OtherMenuEntity} from '../models';
import {MainRouteConfig} from 'config/RouteConfig';

const OtherMenuConfig: Array<OtherMenuEntity> = [
  new OtherMenuEntity(
    'report_performance',
    ic_report,
    'Báo cáo hiệu suất',
    OtherMenuType.ReportPersonal,
    null,
    false,
    MainRouteConfig.ReportPerformance,
  ),
  new OtherMenuEntity(
    'personnel_target',
    ic_target,
    'Mục tiêu cá nhân',
    OtherMenuType.ReportPersonal,
    null,
    true,
    '',
  ),
  new OtherMenuEntity(
    'report_retail',
    ic_package_delivery,
    'Báo cáo bán lẻ',
    OtherMenuType.ReportPersonal,
    null,
    false,
    MainRouteConfig.ReportRetail,
  ),
  new OtherMenuEntity(
    'order_report',
    ic_package_delivery1,
    'Báo cáo đơn hàng',
    OtherMenuType.ReportPersonal,
    null,
    true,
    '',
  ),
  new OtherMenuEntity(
    'report_conversion',
    ic_reload,
    'Báo cáo chuyển đổi',
    OtherMenuType.ReportPersonal,
    null,
    false,
    MainRouteConfig.ReportConversion,
  ),
  // new OtherMenuEntity(
  //   'customer_list',
  //   ic_id_card,
  //   'Danh sách khách hàng',
  //   OtherMenuType.ReportGeneral,
  //   null,
  //   false,
  //   MainRouteConfig.CustomerList,
  // ),
  new OtherMenuEntity(
    'lot_manager',
    ic_check_list,
    'Quản lý lốt khách',
    OtherMenuType.ReportGeneral,
    null,
    false,
    MainRouteConfig.FeedbackRecord,
  ),
  new OtherMenuEntity(
    'product_positioning',
    ic_interaction,
    'Chuyển vị trí sản phẩm',
    OtherMenuType.ReportGeneral,
    null,
    true,
    MainRouteConfig.ProductPositioning,
  ),
  new OtherMenuEntity(
    'timekeeping',
    ic_location_grey,
    'Chấm công định vị',
    OtherMenuType.Extension,
    null,
    false,
    MainRouteConfig.TimeSheet,
    true,
  ),
  new OtherMenuEntity(
    'application_form',
    ic_form_list,
    'Đơn từ',
    OtherMenuType.Extension,
    null,
    false,
    MainRouteConfig.SingleWord,
    true,
  ),
  new OtherMenuEntity(
    'task_management',
    ic_task_management_grey,
    'Checklist công việc',
    OtherMenuType.Extension,
    null,
    false,
    MainRouteConfig.TaskManagement,
  ),
  new OtherMenuEntity(
    'wall_feedback',
    ic_delete_account,
    'Bức tường lông ngỗng',
    OtherMenuType.Extension,
    null,
    false,
    MainRouteConfig.WallFeedback,
  ),
  new OtherMenuEntity(
    'feedback',
    ic_heart,
    'Đề xuất góp ý',
    OtherMenuType.Extension,
    null,
    false,
    MainRouteConfig.Feedback,
  ),
  new OtherMenuEntity(
    'support_user',
    ic_alert,
    'Hỗ trợ người dùng',
    OtherMenuType.Extension,
    null,
    false,
    MainRouteConfig.UserSupport,
  ),
  new OtherMenuEntity(
    'phone_book',
    ic_phonebook,
    'Danh bạ',
    OtherMenuType.Extension,
    null,
    false,
    '',
  ),
  new OtherMenuEntity(
    'account_store',
    ic_store_default,
    'Cửa hàng mặc định',
    OtherMenuType.Setting,
    null,
    false,
    MainRouteConfig.AccountStore,
  ),
  new OtherMenuEntity(
    'config',
    ic_setting,
    'Cấu hình',
    OtherMenuType.Setting,
    null,
    true,
    '',
  ),
  new OtherMenuEntity(
    'help',
    ic_help,
    'Trợ giúp',
    OtherMenuType.Setting,
    null,
    true,
    MainRouteConfig.Help,
  ),
  new OtherMenuEntity(
    'version_product',
    ic_device,
    'Phiên bản sản phẩm',
    OtherMenuType.Setting,
    null,
    true,
    MainRouteConfig.VersionInformation,
  ),
  new OtherMenuEntity(
    'request_delete_account',
    icon_user,
    'Yêu cầu xoá tài khoản',
    OtherMenuType.Setting,
    null,
    true,
    MainRouteConfig.VersionInformation,
  ),
];

export default OtherMenuConfig;
