import {
  bleach_any,
  clean_dry_f,
  clean_dry_f_mild,
  clean_dry_p,
  clean_dry_p_mild,
  clean_wet,
  clean_wet_mild,
  clean_wet_very_mild,
  dry_60,
  dry_80,
  dry_flat,
  dry_flat_drip,
  dry_flat_drip_shade,
  dry_flat_shade,
  dry_line,
  dry_line_drip,
  dry_line_drip_shade,
  dry_line_shade,
  iron_110,
  iron_150,
  iron_200,
  no_bleach,
  no_clean_dry,
  no_clean_wet,
  no_dry,
  no_iron,
  no_wash,
  wash_30,
  wash_30_mild,
  wash_30_very_mild,
  wash_40,
  wash_40_mild,
  wash_40_very_mild,
  wash_50,
  wash_50_mild,
  wash_60,
  wash_60_mild,
  wash_70,
  wash_95,
  wash_hand,
} from 'assets/images';
import {CareLabelEntity} from '../models';

const CareLabelConfigs = [
  new CareLabelEntity('bleach-any', bleach_any, 'Có thể sử dụng chất tẩy'),
  new CareLabelEntity(
    'clean-dry-f-mild',
    clean_dry_f_mild,
    'Giặt khô nhẹ nhàng trong hydrocacbon',
  ),
  new CareLabelEntity('clean-dry-f', clean_dry_f, 'Giặt khô trong hydrocacbon'),
  new CareLabelEntity(
    'clean-dry-p-mild',
    clean_dry_p_mild,
    'Giặt khô nhẹ nhàng trong tetracloetylen',
  ),
  new CareLabelEntity(
    'clean-dry-p',
    clean_dry_p,
    'Giặt khô trong tetracloetylen',
  ),
  new CareLabelEntity(
    'clean-wet-mild',
    clean_wet_mild,
    'Giặt ướt chuyên nghiệp, nhẹ nhàng',
  ),
  new CareLabelEntity(
    'clean-wet-very-mild',
    clean_wet_very_mild,
    'Giặt ướt chuyên nghiệp, rất nhẹ nhàng',
  ),
  new CareLabelEntity('clean-wet', clean_wet, 'Giặt ướt chuyên nghiệp'),
  new CareLabelEntity(
    'dry-60',
    dry_60,
    'Có thể sấy khô, nhiệt độ tối đa 60 độ C',
  ),
  new CareLabelEntity(
    'dry-80',
    dry_80,
    'Có thể sấy khô, nhiệt độ tối đa 80 độ C',
  ),
  new CareLabelEntity(
    'dry-flat-drip-shade',
    dry_flat_drip_shade,
    'Phơi trải phẳng, không vắt, trong bóng râm',
  ),
  new CareLabelEntity(
    'dry-flat-drip',
    dry_flat_drip,
    'Phơi trải phẳng, không vắt',
  ),
  new CareLabelEntity(
    'dry-flat-shade',
    dry_flat_shade,
    'Phơi trải phẳng, trong bóng râm',
  ),
  new CareLabelEntity('dry-flat', dry_flat, 'Phơi trải phẳng'),
  new CareLabelEntity(
    'dry-line-drip-shade',
    dry_line_drip_shade,
    'Phơi dây, không vắt, trong bóng râm',
  ),
  new CareLabelEntity('dry-line-drip', dry_line_drip, 'Phơi dây, không vắt'),
  new CareLabelEntity(
    'dry-line-shade',
    dry_line_shade,
    'Phơi dây, trong bóng râm',
  ),
  new CareLabelEntity('dry-line', dry_line, 'Phơi dây'),
  new CareLabelEntity(
    'iron-110',
    iron_110,
    'Có thể ủi, nhiệt độ tối đa 110 độ C',
  ),
  new CareLabelEntity(
    'iron-150',
    iron_150,
    'Có thể ủi, nhiệt độ tối đa 150 độ C',
  ),
  new CareLabelEntity(
    'iron-200',
    iron_200,
    'Có thể ủi, nhiệt độ tối đa 200 độ C',
  ),
  new CareLabelEntity('no-bleach', no_bleach, 'Không được tẩy'),
  new CareLabelEntity('no-clean-dry', no_clean_dry, 'Không được giặt khô'),
  new CareLabelEntity('no-clean-wet', no_clean_wet, 'Không được giặt ướt'),
  new CareLabelEntity('no-dry', no_dry, 'Không được sấy'),
  new CareLabelEntity('no-wash', no_wash, 'Không được giặt'),
  new CareLabelEntity(
    'wash-30-mild',
    wash_30_mild,
    'Giặt nhẹ nhàng, nhiệt độ tối đa 30 độ C',
  ),
  new CareLabelEntity(
    'wash-30-very-mild',
    wash_30_very_mild,
    'Giặt rất nhẹ nhàng, nhiệt độ tối đa 30 độ C',
  ),
  new CareLabelEntity('wash-30', wash_30, 'Giặt máy, nhiệt độ tối đa 30 độ C'),
  new CareLabelEntity(
    'wash-40-mild',
    wash_40_mild,
    'Giặt nhẹ nhàng, nhiệt độ tối đa 40 độ C',
  ),
  new CareLabelEntity(
    'wash-40-very-mild',
    wash_40_very_mild,
    'Giặt rất nhẹ nhàng, nhiệt độ tối đa 40 độ C',
  ),
  new CareLabelEntity('wash-40', wash_40, 'Giặt máy, nhiệt độ tối đa 40 độ C'),
  new CareLabelEntity(
    'wash-50-mild',
    wash_50_mild,
    'Giặt nhẹ nhàng, nhiệt độ tối đa 50 độ C',
  ),
  new CareLabelEntity('wash-50', wash_50, 'Giặt máy, nhiệt độ tối đa 50 độ C'),
  new CareLabelEntity(
    'wash-60-mild',
    wash_60_mild,
    'Giặt nhẹ nhàng, nhiệt độ tối đa 60 độ C',
  ),
  new CareLabelEntity('wash-60', wash_60, 'Giặt máy, nhiệt độ tối đa 60 độ C'),
  new CareLabelEntity('wash-70', wash_70, 'Giặt máy, nhiệt độ tối đa 70 độ C'),
  new CareLabelEntity('wash-95', wash_95, 'Giặt máy, nhiệt độ tối đa 95 độ C'),
  new CareLabelEntity(
    'wash-hand',
    wash_hand,
    'Giặt tay, nhiệt độ tối đa 40 độ C',
  ),
  new CareLabelEntity('no-iron', no_iron, 'Không được ủi'),
];

export default CareLabelConfigs;
