export enum AsyncStorageKey {
  ON_BOARD = '@ON_BOARD',
  STORE_ACTIVATED = '@STORE_ACTIVATED/v1',
  COUNTRY = '@COUNTRY1',
  DISTRICT = '@DISTRICT1',
  CITIES = '@CITIES',
  WARD = '@WARD',
  ON_BOARD_REPORT = '@ON_BOARD_REPORT',
  FCM = '@FCM',
  YOSCAN_ORDER = '@YOSCAN_ORDER',
  TAB_ORDER_ACTIVE = '@TAB_ORDER_ACTIVE',
}
