export interface CustomerResponse {
  id: number;
  code: string;
  assignedDate: string | null;
  assignedStore: string | null;
  assignedStoreId: number | null;
  averageOrderAmount: number | null;
  birthday: number | null;
  birthdayCompare: number | null;
  birthdayDayAndMonthCompare: number | null;
  birthdayDayAndYearCompare: number | null;
  birthdayMonthAndYearCompare: number | null;
  cardNumber: string | null;
  channelIds: Array<string> | null;
  city: string | null;
  cityId: number | null;
  company: string | null;
  customerGroup: string | null;
  customerGroupId: number | null;
  customerLevel: string | null;
  customerLevelId: number | null;
  customerRelationship: string | null;
  customerType: string | null;
  customerTypeId: number | null;
  dayOfBirth: number | null;
  district: string | null;
  districtId: number | null;
  ecommerceUid: string | null;
  email: string | null;
  familyInfo: string | null;
  firstOrderTime: string | null;
  firstOrderTimeOffline: string | null;
  firstOrderTimeOnline: string | null;
  firstOrderType: string | null;
  fullAddress: string;
  fullName: string;
  gender: string;
  grossSale: string | null;
  identityNumber: string | null;
  lastOrderTime: string | null;
  lastOrderTimeOffline: string | null;
  lastOrderTimeOnline: string | null;
  lastOrderType: string | null;
  monthOfBirth: number | null;
  phone: string;
  point: number | null;
  responsibleStaff: null | string;
  responsibleStaffCode: null | string;
  sourceIdOfFirstOrderOnline: null | number;
  sourceIdOfLastOrderOnline: null | number;
  sourceIds: Array<number> | null;
  sourceOfFirstOrderOnline: null | string;
  sourceOfLastOrderOnline: null | string;
  storeIdOfFirstOrderOffline: null | Array<number>;
  storeIdOfLastOrderOffline: null | Array<number>;
  storeIds: null | Array<number>;
  storeOfFirstOrderOffline: number | null;
  storeOfLastOrderOffline: number | null;
  totalFinishedOrder: number | null;
  totalOrderHasGrossSale: number | null;
  totalPaidAmount: number | null;
  totalRefundedAmount: number | null;
  totalReturnedOrder: number | null;
  utmCampaign: string | null;
  utmContent: string | null;
  utmId: string | null;
  utmMedium: string | null;
  utmSource: string | null;
  utmTerm: string | null;
  ward: string | null;
  wardId: number | null;
  website: string | null;
  weddingDate: string | null;
  weddingDay: number | null;
  weddingMonth: number | null;
  weddingYear: number | null;
  yearOfBirth: number | null;
}
export interface CreateCustomerResponse {
  id: number;
  code: string;
  version: number;
  created_by: string;
  created_name: string;
  created_date: string;
  updated_by: string;
  updated_name: string;
  updated_date: string;
  full_name: string;
  phone: string;
  email: string;
  customer_group_id: number;
  customer_group: string;
  customer_type_id: number;
  customer_type: string;
  company_id: number;
  company: string;
  website: string;
  description: string;
  customer_level_id: number;
  customer_level: string;
  status: string;
  wedding_date: string;
  birthday: string;
  gender: string;
  responsible_staff_code: string;
  responsible_staff: string;
  tags: string;
  notes: string;
  tax_code: string;
  country_id: number;
  country: string;
  city_id: number;
  city: 'TP. Hà Nội';
  district_id: 1;
  district: 'Quận Thanh Xuân';
  ward_id: 1;
  ward: 'Phường Hạ Đình';
  zip_code: null;
  full_address: 'Số 3';
  card_number: '12433456789';
  channel: null;
  channel_id: null;
  channel_code: null;
  source: null;
  source_id: null;
  source_code: null;
  billing_addresses: [
    {
      id: null;
      code: 'gjRerjyodbGE';
      version: 0;
      created_by: 'YD99999';
      created_name: 'Quản trị viên';
      created_date: '2023-03-08T09:20:22Z';
      updated_by: 'YD99999';
      updated_name: 'Quản trị viên';
      updated_date: '2023-03-08T09:20:22Z';
      name: 'Duong Tung Nguyen';
      email: 'duongk22899@gmail.com';
      phone: '0339282828';
      country_id: 233;
      country: 'VIETNAM';
      city_id: 1;
      city: 'TP. Hà Nội';
      district_id: 1;
      district: 'Quận Thanh Xuân';
      ward_id: 1;
      ward: 'Phường Hạ Đình';
      zip_code: null;
      full_address: 'Số 3';
      tax_code: '12234565676789';
      buyer: null;
      default: true;
    },
  ];
  shipping_addresses: [
    {
      id: null;
      code: 'Kqt5PiShXFZn';
      version: 0;
      created_by: 'YD99999';
      created_name: 'Quản trị viên';
      created_date: '2023-03-08T09:20:22Z';
      updated_by: 'YD99999';
      updated_name: 'Quản trị viên';
      updated_date: '2023-03-08T09:20:22Z';
      name: 'Duong Tung Nguyen';
      email: 'duongk22899@gmail.com';
      phone: '0339282828';
      country_id: 233;
      country: 'VIETNAM';
      city_id: 1;
      city: 'TP. Hà Nội';
      district_id: 1;
      district: 'Quận Thanh Xuân';
      ward_id: 1;
      ward: 'Phường Hạ Đình';
      zip_code: null;
      full_address: 'Số 3';
      default: true;
    },
  ];
  contacts: [
    {
      id: null;
      code: '1';
      version: 0;
      created_by: 'YD99999';
      created_name: 'Quản trị viên';
      created_date: '2023-03-08T09:20:22Z';
      updated_by: 'YD99999';
      updated_name: 'Quản trị viên';
      updated_date: '2023-03-08T09:20:22Z';
      title: null;
      name: 'lienhe';
      email: 'lienhe@gmail.com';
      phone: '0339999999';
      note: 'ghi chu lien he';
    },
  ];
  report: null;
  assigned_store_id: null;
  assigned_store: null;
  identity_number: '142857489';
  utm: null;
  assigned_date: '2023-03-08T09:20:22Z';
  point: null;
  region_code: '84';
  ecommerce_uid: null;
  customer_relationship: null;
  family_info: null;
}
