import {MainRouteConfig} from 'config/RouteConfig';
import {ChannelDetailEntity} from '../models';

const ChannelDetailConfig: Array<ChannelDetailEntity> = [
  new ChannelDetailEntity(
    1,
    'create',
    'Tạo đơn Yoscan',
    1,
    false,
    true,
    MainRouteConfig.PosCreate,
    true,
  ),
  new ChannelDetailEntity(
    2,
    'listYoscan',
    'Danh sách đơn Yoscan',
    1,
    false,
    false,
    MainRouteConfig.YoscanList,
    false,
  ),
  new ChannelDetailEntity(
    3,
    'list',
    'Danh sách đơn bán tại quầy',
    1,
    false,
    false,
    MainRouteConfig.PosList,
    false,
  ),
  new ChannelDetailEntity(
    6,
    'list_o2o',
    'Danh sách đơn O2O',
    1,
    false,
    false,
    MainRouteConfig.O2OList,
    false,
  ),
  new ChannelDetailEntity(
    9,
    'return',
    'Danh sách đơn trả tại quầy',
    1,
    false,
    false,
    MainRouteConfig.PosReturnList,
    false,
  ),
  new ChannelDetailEntity(
    11,
    'create',
    'Tạo đơn bán online',
    2,
    true,
    false,
    MainRouteConfig.AdminCreate,
    false,
  ),
  new ChannelDetailEntity(
    13,
    'list',
    'Danh sách đơn bán online',
    2,
    true,
    false,
    MainRouteConfig.AdminList,
    false,
  ),
  new ChannelDetailEntity(
    15,
    'return',
    'Danh sách đơn trả online',
    2,
    true,
    false,
    MainRouteConfig.AdminReturn,
    false,
  ),
];

export default ChannelDetailConfig;
