import {BaseDto} from 'model/base/BaseDto';
import {BillingAddressSubDto} from './BillingAddressSubDto';
import {DiscountReasonDto} from './DiscountReasonSubDto';
import {DiscountSubDto} from './DiscountSubDto';
import {LineItemSubDto} from './LineItemSubDto';
import {PaymentSubDto} from './PaymentSubDto';
import {ReasonSubDto} from './ReasonSubDto';
import {ShippingAddressSubDto} from './ShippingAddressSubDto';
import {SubReasonSubDto} from './SubReasonSubDto';

export interface OrderReturnDto extends BaseDto {
  account: string | null;
  accountCode: string | null;
  assignee: string | null;
  assigneeCode: string | null;
  billingAddress: BillingAddressSubDto | null;
  cancelAccountCode: string | null;
  cancelledOn: string | null;
  channel: string | null;
  channelId: number | null;
  company: string;
  companyId: number;
  currency: string;
  customer: string;
  customerEmail: string | null;
  customerId: number;
  customerNote: string | null;
  customerPhoneNumber: string | null;
  discountReason: DiscountReasonDto;
  discounts: Array<DiscountSubDto>;
  expectedDeliveryProviderId: number | null;
  expectedDeliveryType: string | null;
  expectedPaymentMethodId: number | null;
  finalizedAccountCode: string | null;
  finalizedOn: string | null;
  finishAccountCode: string | null;
  finishedOn: string | null;
  items: Array<LineItemSubDto>;
  marketer: string | null;
  marketerCode: string | null;
  moneyAmount: number;
  moneyRefund: number;
  note: string;
  orderCode: string;
  orderDiscountRate: number | null;
  orderDiscountValue: number | null;
  orderExchangeId: number | null;
  orderId: number;
  otherReason: string | null;
  paymentMethod: string | null;
  paymentMethodId: number | null;
  paymentStatus: string;
  payments: Array<PaymentSubDto>;
  pointRefund: number;
  priceType: string;
  reason: ReasonSubDto;
  reasonId: number | null;
  reasonName: string | null;
  receiveDate: string | null;
  received: boolean;
  referenceCode: string | null;
  referent: null;
  returnDate: string | null;
  returnedStoreId: number | null;
  saleNote: string | null;
  shippingAddress: ShippingAddressSubDto;
  source: string | null;
  sourceId: number | null;
  status: string;
  store: string | null;
  storeFullAddress: string | null;
  storeId: number | null;
  storePhoneNumber: string | null;
  subReason: SubReasonSubDto | null;
  subReasonId: number | null;
  subReasonName: string | null;
  tags: string;
  taxTreatment: string | null;
  total: number;
  totalAmount: number | null;
  totalDiscount: number;
  totalLineAmountAfterLineDiscount: number | null;
  totalQuantities: number;
  totalTax: number | null;
  url: string | null;
}
